apiVersion: apps/v1                # Phiên bản API Kubernetes sử dụng (apps/v1)
kind: Deployment                   # Loại tài nguyên (Deployment quản lý việc triển khai ứng dụng)
metadata:                          # Thông tin mô tả về Deployment
  name: demo-app                   # Tên của Deployment
  labels:                          # Nhãn để nhận dạng Deployment
    app: demo-app                  # Nhãn key-value: app=demo-app
spec:                              # Đặc tả cách triển khai
  replicas: 1                      # Số lượng bản sao (pods) sẽ được tạo và duy trì
  selector:                        # Cách Deployment xác định các pods thuộc về nó
    matchLabels:                   # Chọn pods có nhãn phù hợp
      app: demo-app                # Pods phải có nhãn app=demo-app
  template:                        # Mẫu để tạo pods mới
    metadata:                      # Thông tin mô tả cho pods được tạo
      labels:                      # Nhãn áp dụng cho pods
        app: demo-app              # Mỗi pod sẽ có nhãn app=demo-app
    spec:                          # Đặc tả cấu hình pod
      containers:                  # Danh sách các containers trong mỗi pod
        - name: demo-app           # Tên container
          image: duytc81811/demo:latest  # Image Docker sử dụng
          ports:                    # Cổng mà container sử dụng
            - containerPort: 3000   # Container lắng nghe trên cổng 3000
---
apiVersion: v1                     # Phiên bản API Kubernetes sử dụng (v1)
kind: Service                      # Loại tài nguyên (Service để truy cập vào ứng dụng)
metadata:                          # Thông tin mô tả về Service
  name: demo-app-service           # Tên của Service
  labels:                          # Nhãn để nhận dạng Service
    app: demo-app                  # Nhãn key-value: app=demo-app
spec:                              # Đặc tả cấu hình Service
  selector:                        # Chọn pods mà Service sẽ định tuyến traffic đến
    app: demo-app                   # Chọn pods có nhãn app=demo-app
  ports:                           # Cấu hình cổng
    - name: http
    - protocol: TCP
    - port: 80                     # Cổng mà Service sẽ lắng nghe
      targetPort: 3000             # Cổng trên pod mà Service sẽ chuyển tiếp traffic đến
  type: NodePort                   # ClusterIP: chỉ truy cập được trong cluster, NodePort: bất kể ip của node, LoadBalancer: từ cloud provider

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/path-rewrite: /
    # Chuyển hướng HTTP sang HTTPS
    haproxy.org/ssl-redirect: "true"
    # Buộc sử dụng HTTPS
    haproxy.org/ssl-passthrough: "false"
    # Thiết lập HSTS để hướng dẫn trình duyệt luôn sử dụng HTTPS
    haproxy.org/hsts: "true"
    haproxy.org/hsts-max-age: "15768000"
    haproxy.org/hsts-include-subdomains: "true"
    haproxy.org/hsts-preload: "true"
spec:
  tls:
    - hosts:
        - demo-app.example.com
      secretName: demo-app-tls-secret
  rules:
    - host: demo-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-app-service
                port:
                  number: 80
