name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Bước 1: Clone mã nguồn
      -
        name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Node.js
      -
        name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Bước 3: Cache thư viện Node.js
      -
        name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      # Bước 4: Cài đặt dependencies
      -
        name: Install dependencies
        run: npm ci

      # Bước 5: Build ứng dụng
      -
        name: Build application
        run: npm run build --if-present

      # Bước 6: Đăng nhập vào Docker Hub
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: duytc81811/demo:latest

#      # Bước 9: Gửi thông báo Telegram khi thất bại
#      - name: Notify Telegram
#        uses: appleboy/telegram-action@master
#        if: failure()
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ❌ **Build failed!**
#            - Pull Request By: ${{ github.event.pull_request.user.login }}
#            - Title: ${{ github.event.pull_request.title }}

#  deployment:
#    runs-on: ubuntu-latest
#    needs: build-and-push-docker                          # Chỉ chạy khi job 'build-and-push-docker' thành công
#    name: Deploy to Server
#
#    steps:
#      # Clone mã nguồn
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      # Thực hiện deploy qua SSH
#      - name: Execute SSH commands on remote server
#        run: |
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem && chmod 600 keypair.pem
#          ssh -o StrictHostKeyChecking=no -i keypair.pem ${{ secrets.SSH_HOST }} '
#          docker compose -f docker-compose.yml pull &&
#          docker compose -f docker-compose.yml up -d --remove-orphans'
#
#      # Gửi thông báo Telegram Success
#      - name: Notify Telegram
#        uses: appleboy/telegram-action@master
#        if: success()
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            🎉 Deployment Succeeded!
#            - Pull Request By: ${{ github.event.pull_request.user.login }}
#            - Title: ${{ github.event.pull_request.title }}
#
#      # Gửi thông báo Telegram Nếu Failure
#      - name: Notify Telegram
#        uses: appleboy/telegram-action@master
#        if: failure()
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ❌ Deployment Failure!
#            - Pull Request By: ${{ github.event.pull_request.user.login }}
#            - Title: ${{ github.event.pull_request.title }}
